__author__ = 'tony'

TWITTER_MAX_LIST_SIZE=5000
TWITTER_MAX_NUMBER_OF_LISTS=180#can be changed to 1000 but retrieval of tweets from all lists not guaranteed
TWITTER_MAX_NUMBER_OF_NON_FOLLOWED_USERS=300
TWITTER_BULK_LIST_SIZE=100
TWITTER_MAX_NUM_OF_BULK_LISTS=60
TWITTER_MAX_NUM_OF_REQUESTS_PER_CYCLE=180